### ISSUE TITLE
Release 

### ISSUE THREAD

**Issue by aarvndhNG** [Qianyiovo/PrismBot#1]
Is there any release

**Comment by Arispex** [comment]
> Is there any release 

Yes, but this project is not finished yet, it is more like a bot framework than a bot with integrated functionality, it needs plugins to implement the functionality. It is only available for QQ.

**Comment by aarvndhNG** [comment]
Is it a server plugin or what

**Comment by Arispex** [comment]
> Is it a server plugin or what

It is a chatbot for Tencent QQ.

**Comment by aarvndhNG** [comment]
Oh ok

**Comment by aarvndhNG** [comment]
Are u Chinese

**Comment by Arispex** [comment]
> Are u Chinese 

yeah

**Comment by aarvndhNG** [comment]
Noice can you help me

**Comment by aarvndhNG** [comment]
@Qianyiovo

**Comment by Arispex** [comment]
> Noice can you help me 

What is it

**Comment by aarvndhNG** [comment]
Can you translate some Chinese plugin please sir

**Comment by aarvndhNG** [comment]
Please 🙏

**Comment by aarvndhNG** [comment]
I can also help u

**Comment by aarvndhNG** [comment]
@Qianyiovo

**Comment by Arispex** [comment]
> I can also help u

What can you do to help me?

**Comment by aarvndhNG** [comment]
Iam using mobile so i can only translate to English but i can't make plugin so i need your help sir

**Comment by Arispex** [comment]
> Can you translate some Chinese plugin please sir

Translating Chinese plugin is easy, you just need to replace the text.

**Comment by aarvndhNG** [comment]
Yes i know ibut i can't make tshock plugin

**Comment by aarvndhNG** [comment]
@Qianyiovo

**Comment by aarvndhNG** [comment]
I think u can't help me 😔😢

**Comment by Arispex** [comment]
> Yes i know ibut i can't make tshock plugin 

Why not try using a cloud server to compile your code

**Comment by aarvndhNG** [comment]
Idk how?

**Comment by Arispex** [comment]
> Idk how?

You can search for tutorials in Google, or if your cloud server is Linux, try searching for "how to compile Dotnet6 on Linux". If it's Windows, it's even easier, you can just download Visual Studio.

**Comment by aarvndhNG** [comment]
Iam mobile

**Comment by aarvndhNG** [comment]
I'll edit the file what you say and u will make the plugin

**Comment by aarvndhNG** [comment]
> > Idk how?
> 
> You can search for tutorials in Google, or if your cloud server is Linux, try searching for "how to compile Dotnet6 on Linux". If it's Windows, it's even easier, you can just download Visual Studio.

I didn't have enough time to do this so please help me please

**Comment by Arispex** [comment]
> I'll edit the file what you say and u will make the plugin 

The most I can do is to compile the code for you. Please let me know your discord or telegram.

**Comment by aarvndhNG** [comment]
Oh ok wait

**Comment by aarvndhNG** [comment]
Discord GoldenWolf#9191

**Comment by aarvndhNG** [comment]
Request me on discord @Qianyiovo

**Comment by aarvndhNG** [comment]
Can I close this issue

**Comment by Arispex** [comment]
> Can I close this issue 

Yeah
