### ISSUE TITLE
Lot of plugin 

### ISSUE THREAD

**Issue by aarvndhNG** [Qianyiovo/PrismBot#4]
Can you make it in small please because it's lot of plugin.....!

**Comment by Arispex** [comment]
You don't need it.it is not TShock plugin.

**Comment by aarvndhNG** [comment]
What

**Comment by LaoSparrow** [comment]
This project is an independent software from TShock and it's not a TShock plugin.
It's quite like a manager that helps the owners to control their server through a Chinese IM called "QQ".
This project has not support multi-languages yet and you probably won't use QQ, so you won't need it.

**Comment by aarvndhNG** [comment]
Ohhhh 😲 sorry my bad 😞....!
