### ISSUE TITLE
获取在线失败

### ISSUE THREAD

**Issue by qwjp1234** [Qianyiovo/PrismBot#5]
添加服务器 <服务器IP/域名> <服务器REST端口> <REST TOKEN> <对外显示昵称> <标识符>其中<REST TOKEN>的格式怎么添加。
![image](https://user-images.githubusercontent.com/93645806/226533915-06095b28-3070-4001-b01a-7eab216405bd.png)
![image](https://user-images.githubusercontent.com/93645806/226534038-3aba7515-38b6-4b45-b840-fde44ce882d5.png)
![image](https://user-images.githubusercontent.com/93645806/226534067-25def22b-85a8-40b4-b418-3675a0dd2263.png)

**Comment by qwjp1234** [comment]
插件是加上的

**Comment by Arispex** [comment]
面板服？Rest端口放行了吗？

**Comment by qwjp1234** [comment]
没设置过，在百度怎么搞

**Comment by Arispex** [comment]
那还是建议先了解一下 TShock 的 REST API

**Comment by qwjp1234** [comment]
hh,想起来了好久没配置过泰拉了，以前是看呆呆小沫的教程。我再去试试
