### ISSUE TITLE
白名单添加Bug

### ISSUE THREAD

**Issue by qwjp1234** [Qianyiovo/PrismBot#6]
我又来问问题了。
![4JJV078MBO D%E9`KWFU`FQ](https://user-images.githubusercontent.com/93645806/227473667-f229b6e9-913a-455c-8622-02e6935209e3.png)
![U85`AWIT9TBDC)YY6OG3J34](https://user-images.githubusercontent.com/93645806/227473688-61feab97-1fbf-4a52-894e-f8302de89c39.png)
![M`H
![Screenshot_2023-03-24-17-01-05-963_com and games5](https://user-images.githubusercontent.com/93645806/227473724-8e8668b4-6377-451c-ba55-25a251c2642a.jpg)
{57_HPLZT)U6N _8XQF](https://user-images.githubusercontent.com/93645806/227473703-4a2b94b5-c011-43b6-8b80-ec75b675687b.png)

![J~T6R3AN(QEJU)P9HT7 8AX](https://user-images.githubusercontent.com/93645806/227474386-ef190148-4684-448f-a455-81d83ba734e6.png)

**Comment by qwjp1234** [comment]
白名单问题，用机器人添加后不能进入服务器。怎么解决

**Comment by Arispex** [comment]
有没有可能这不是bug，你瞎改了端口当然连不上

**Comment by Arispex** [comment]
交流群690290280

**Comment by qwjp1234** [comment]
> 有没有可能这不是bug，你瞎改了端口当然连不上

这个面板服有两个端口，我用了另一个没有被占用的。按道理来说是可行的。

**Comment by qwjp1234** [comment]
> 交流群690290280

已申请

**Comment by Arispex** [comment]
这玩意儿要8080和8081两个端口 8081是给tshock服务器通讯用的

**Comment by qwjp1234** [comment]
> 这玩意儿要8080和8081两个端口 8081是给tshock服务器通讯用的

理解了，我就说看文档要预留8081，这个端口没办法开
